### ISSUE TITLE
[BUG] `accounts` table does not exist, must be manually created on first time startup

### ISSUE THREAD

**Issue by Maxattax97** [linuxserver/docker-mastodon#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue is tracked here: https://github.com/mastodon/mastodon/issues/14670

Ideally the LSIO image would handle it for us.

### Expected Behavior

Container initializes database on it's own.

### Steps To Reproduce

1. configure `mastodon` container in docker-compse
2. run it, ensure it properly connects to DB
3. fails because database does not contain expected `accounts` table (and a lot more)

### Environment

```markdown
- OS: Fedora Linux 36 (Server Edition) x86_64
- How docker service was installed: via `dnf`
```

### CPU architecture

x86-64

### Docker creation

```yaml
mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon
    depends_on:
      - redis
      - postgres
    env_file:
      - /opt/flotilla/secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - LOCAL_DOMAIN=mastodon.maxocull.com # Normally this is `maxocull.com`, but I didn't want to dedicate a webfinger to `mastodon.maxocull.com`: https://docs.joinmastodon.org/admin/config/#web_domain
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_TLS=true
      - SMTP_PORT=587
      - SMTP_FROM_ADDRESS=maxocull.com@gmail.com
      - S3_ENABLED=false
      - WEB_DOMAIN=mastodon.maxocull.com #optional
      #- DB_POOL=5 #optional
    volumes:
      - /opt/flotilla/config/mastodon:/config:Z
    ports:
      - "127.0.0.1:9080:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
```

### Container logs
See the initial ticket for the logs.
