### ISSUE TITLE
CSS not rendered

### ISSUE THREAD

**Issue by RainerZufall187** [linuxserver/docker-mastodon#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

Same as #8 except that I'm getting 200 responses on all requested assets
https://mastodon.rainer-zufall.tk/

## Environment
**OS:** Raspberry Pi OS Lite 64bit
**CPU architecture:** arm64
**How docker service was installed:** https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

## Command used to create docker container (run/create/compose/screenshot)

`sudo docker compose up -d`

```yml
version: "3"
services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_PASSWORD=ok2143244325'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - LOCAL_DOMAIN=mastodon.rainer-zufall.tk
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=ok2143244325
      - DB_PORT=5432
      - ES_ENABLED=false
      - SMTP_FROM_ADDRESS=mastodon@rainer-zufall.tk
      - S3_ENABLED=false
      - WEB_DOMAIN=mastodon.rainer-zufall.tk #optional
      - ES_HOST=es #optional
      - ES_PORT=9200 #optional
      - ES_USER=elastic #optional
      - ES_PASS=elastic #optional
      - S3_BUCKET= #optional
      - AWS_ACCESS_KEY_ID= #optional
      - AWS_SECRET_ACCESS_KEY= #optional
      - S3_ALIAS_HOST= #optional

      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - ./mastodon_config:/config
    restart: unless-stopped
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis

  cloudflared:
    image: cloudflare/cloudflared
    restart: always
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel run mastodon
    networks:
      - external_network
      - internal_network
    depends_on:
      - mastodon


networks:
  external_network:
  internal_network:
    internal: true
```
