### ISSUE TITLE
[FEAT] use http_proxy environment variables in docker-compose.yml

### ISSUE THREAD

**Issue by HoshinoSuzumi** [linuxserver/docker-mastodon#99]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The mastodon and sidekiq in the container read variables such as `HTTP_PROXY` `HTTPS_PROXY` `NO_PROXY` in env and try to use these proxies for queue operations.

### Reason for change

In some special network environments(In Chinese mainland, some websites are blocked), the queue tasks cannot access other instances, but returns errors: `HTTP::ConnectionError: failed to connect: Host is unreachable`, `HTTP::TimeoutError: Read timed out after 5 seconds on...` etc. Use `curl -vvv xxx.com` of course it cannot be connected.

But I try to configure `docker-compose.yml` like this (the proxy service runs on the host, host's IP is `172.17.0.1`):

```yml
services:
  mastodon:
    image: linuxserver/mastodon:latest
    container_name: mastodon
    networks:
      - external_network
      - internal_network
    environment:
      # ...
      - HTTP_PROXY=http://172.17.0.1:8889
      - HTTPS_PROXY=http://172.17.0.1:8889
      - ALL_PROXY=socks5://172.17.0.1:8891
      - NO_PROXY=127.0.0.1,localhost
    # ...
```

then I tried `docker exec -it mastodon /bin/bash -c 'curl -I https://www.google.com'`, it works and responses

```
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-Y7BvwRsFDz0ojCGrKnV9BQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Tue, 29 Oct 2024 19:03:25 GMT
server: gws
...
```

But now the queue of mastodon instances is still inaccessible to some instances, and there is no new traffic and connection to the host's proxy service.

I also tried enable TUN mode, but I can't seem to access mastodon instances from outside in this mode.

I'm not sure if this is a bug or normal, so I opened this feature issue.

If possible, I would like to know how to configure it to achieve the above effect, or to implement related new features.
